Refactor iOS build process: simplify Ruby script for fetching team information using a one-liner

diff --git a/.github/workflows/build-ios.yml b/.github/workflows/build-ios.yml
--- a/.github/workflows/build-ios.yml
+++ b/.github/workflows/build-ios.yml
@@ -121,38 +121,27 @@ jobs:
             export FASTLANE_PASSWORD="$APPLE_APP_PASSWORD"
             export FASTLANE_DONT_STORE_PASSWORD=1
 
-            # Create a Ruby script to fetch team info using Spaceship
-            cat > /tmp/get_teams.rb << 'EOF'
-            require 'spaceship'
-            begin
+            # Use a simple one-liner to get team info
+            ruby -r spaceship -e "
               Spaceship::Portal.login(ENV['FASTLANE_USER'], ENV['FASTLANE_PASSWORD'])
               teams = Spaceship::Portal.client.teams
-              puts ""
-              puts "=" * 60
-              puts "FOUND YOUR TEAM(S):"
-              puts "=" * 60
+              puts ''
+              puts '=' * 60
+              puts 'FOUND YOUR TEAM(S):'
+              puts '=' * 60
               teams.each do |team|
-                puts "Team Name: #{team['name']}"
-                puts "Team ID:   #{team['teamId']}"
-                puts "Type:      #{team['type']}"
-                puts "-" * 60
+                puts 'Team Name: ' + team['name']
+                puts 'Team ID:   ' + team['teamId']
+                puts 'Type:      ' + team['type']
+                puts '-' * 60
               end
-              puts ""
-              puts "ADD THIS SECRET TO GITHUB:"
-              puts "  Name:  APPLE_TEAM_ID"
-              puts "  Value: #{teams.first['teamId']}"
-              puts ""
-              puts "=" * 60
-            rescue => e
-              puts "Error fetching teams: #{e.message}"
-              puts ""
-              puts "You can also find your Team ID at:"
-              puts "https://developer.apple.com/account"
-            end
-            EOF
-
-            # Run the script
-            ruby /tmp/get_teams.rb || echo "Could not fetch teams automatically"
+              puts ''
+              puts 'ADD THIS SECRET TO GITHUB:'
+              puts '  Name:  APPLE_TEAM_ID'
+              puts '  Value: ' + teams.first['teamId']
+              puts ''
+              puts '=' * 60
+            " 2>&1 || echo "Could not fetch teams automatically. Visit https://developer.apple.com/account"
 
             echo ""
             echo "Once you have your Team ID:"
